env:
  pyinstaller_version: 4.7
  main: main

name: Test Process
on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: Package Application Windows
    #  uses: JackMcKew/pyinstaller-action-windows@main
    #  with:
    #    path: '.'

    - name: setup python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        pip install pyinstaller==${{ env.pyinstaller_version }}
        pyinstaller --clean -y --dist ./dist --onefile ${{ env.main }}.py
        chown -R --reference=. ./dist